image: Visual Studio 2017

configuration:
- Release

before_build:
    - git clone https://github.com/SFML/SFML.git
    - cd SFML
    - mkdir install
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=../install ..
    - msbuild INSTALL.vcxproj
    - cd ../../
    - ls -la

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\tests.exe'