image: Visual Studio 2017

configuration:
- Release

before_build:
    - curl http://mirror2.sfml-dev.org/files/SFML-2.4.2-windows-vc14-32-bit.zip
    - ls -la

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\tests.exe'